SET TERM ^ ;

CREATE OR ALTER PROCEDURE EXTEND_COMPRASBY (
    I_ID_COMPRADOR DOM_INTEGER,
    I_CD_EMPRESA DOM_INTEGER,
    I_NR_COTACAO DOM_INTEGER,
    I_CD_ITEM DOM_INTEGER,
    I_QT_ITEM DOM_NUMERIC15_2,
    I_TP_OPERACAO DOM_CHAR1)
RETURNS (
    O_DS_MENSAGEM DOM_VARCHAR100,
    O_ERROR BOOLEAN,
    O_ID_COTACAO DOM_INTEGER,
    O_CD_EMPRESA DOM_INTEGER,
    O_DS_COTACAO DOM_VARCHAR5000,
    O_NM_PESSOA DOM_VARCHAR100)
AS
DECLARE VARIABLE V_ID_COTACAO DOM_INTEGER;
DECLARE VARIABLE V_CD_EMPRESA DOM_INTEGER;
DECLARE VARIABLE V_DS_COTACAO DOM_VARCHAR5000;
DECLARE VARIABLE V_NM_PESSOA DOM_VARCHAR100;
DECLARE VARIABLE V_MENSAGEM DOM_VARCHAR100;
DECLARE VARIABLE V_USUARIO DOM_VARCHAR10;
BEGIN
    SELECT S.CD_USUARIO
    FROM SESSAO S
    WHERE S.NR_CONEXAO = CURRENT_CONNECTION
    INTO :V_USUARIO;

    IF (:V_USUARIO IS NULL) THEN
    BEGIN
        EXECUTE PROCEDURE GERA_SESSAO RETURNING_VALUES :V_MENSAGEM;
    END
    /*INICIALIZAR VARIAVEL*/
    O_DS_MENSAGEM = '';
    O_ERROR = FALSE;

    /*VALID: VALIDA SE A COTA��O EXISTE*/
    SELECT
        CP.ID, CP.IDEMPRESA, CP.DSCOTACAO, REPLACE(P.NM_PESSOA, '*','') NM_PESSOA
    FROM COTACAOPECA CP
    INNER JOIN PESSOA P ON (P.CD_PESSOA = CP.IDCOMPRADOR)
    WHERE CP.IDEMPRESA = :I_CD_EMPRESA
        AND CP.ID = :I_NR_COTACAO
        AND CP.IDCOMPRADOR = :I_ID_COMPRADOR
        AND CP.STCOTACAO = 'A'
    INTO :V_ID_COTACAO, :V_CD_EMPRESA, :V_DS_COTACAO, :V_NM_PESSOA;

    IF (:V_ID_COTACAO IS NULL) THEN
    BEGIN
        O_DS_MENSAGEM = 'COTAÇÃO NÃO LOCALIZADA, VERIFIQUE!';
        O_ERROR = TRUE;
        SUSPEND;
    END

    /*RETORNA OS DADOS REFERENTE A COTACAO CASO O TP_OPERACAO SEJA V*/
    IF (:I_TP_OPERACAO = 'V') THEN 
    BEGIN
        O_CD_EMPRESA = :V_CD_EMPRESA;
        O_ID_COTACAO = :V_ID_COTACAO;
        O_NM_PESSOA = :V_NM_PESSOA;
        O_DS_COTACAO = :V_DS_COTACAO;
        SUSPEND;
    END

    /*REALIZA A INSERCAO DOS ITEM NA COTACAO*/
    IF (:I_TP_OPERACAO = 'I' AND :V_ID_COTACAO IS NOT NULL) THEN
    BEGIN
        INSERT INTO ITEMCOTACAOPECA (ID, IDCOTACAOPECA, IDITEM, QTDESEJADA, DTREGISTRO, DSOBSERVACAO, VLDESCONTO)
                     VALUES (GEN_ID(SEQ_ITEMCOTACAOPECA, 1), :V_ID_COTACAO, :I_CD_ITEM, :I_QT_ITEM, CURRENT_TIMESTAMP, NULL, NULL);
        O_DS_MENSAGEM = 'COTAÇÃO GERADA COM SUCESSO';
        SUSPEND;
    END

END^

SET TERM ; ^

COMMENT ON PARAMETER EXTEND_COMPRASBY.I_TP_OPERACAO IS
'V - VALIDACAO; I - INSERIR COTACAO';

/* Following GRANT statements are generated automatically */

GRANT USAGE ON SEQUENCE SEQ_ITEMCOTACAOPECA TO PROCEDURE EXTEND_COMPRASBY;
GRANT SELECT ON SESSAO TO PROCEDURE EXTEND_COMPRASBY;
GRANT EXECUTE ON PROCEDURE GERA_SESSAO TO PROCEDURE EXTEND_COMPRASBY;
GRANT SELECT ON COTACAOPECA TO PROCEDURE EXTEND_COMPRASBY;
GRANT SELECT ON PESSOA TO PROCEDURE EXTEND_COMPRASBY;
GRANT INSERT ON ITEMCOTACAOPECA TO PROCEDURE EXTEND_COMPRASBY;

/* Existing privileges on this procedure */

GRANT EXECUTE ON PROCEDURE EXTEND_COMPRASBY TO SYSDBA;